name: SimplePG 결제 API 배포(Azure)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  AZURE_WEBAPP_NAME: 'simplepg-backend'
  
permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: 'https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net'
    
    steps:
    - name: 'Github Actions 체크아웃'
      uses: actions/checkout@v4
      
    - name: 'Java ${{ env.JAVA_VERSION }} 설정'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: 'template -> application.properties 변환'
      run: |
        cp src/main/resources/application.properties.template src/main/resources/application.properties
        echo "application.properties 설정 파일 생성 완료"
        
    - name: 'gradlew 실행 권한 부여'
      run: chmod +x gradlew
      
    - name: 'Gradle 패키지 캐싱'
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: '테스트 실행'
      run: ./gradlew test -Dspring.profiles.active=local
      
    - name: '실제 환경에서의 WAR 빌드'
      run: ./gradlew clean build -x test -Dspring.profiles.active=production
      
    - name: '빌드 출력 확인'
      run: |
        echo "빌드가 성공적으로 완료되었습니다."
        ls -la build/libs/
        echo "WAR file size: $(du -h build/libs/*.war | cut -f1)"
        
    - name: 'Azure 로그인'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_59693BFDBFB54FEFAFD0B9B465EB686E }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CA8D9FF342F248E3B8FEE92CA3132D97 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8790B39689C84C6293791EB6B6E6C7E3 }}
        
    - name: 'Azure 웹 앱에 배포'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: 'build/libs/*.war'
        
    - name: '배포 후 상태 확인'
      run: |
        echo "Azure에 배포가 완료되었습니다"
        echo "앱 URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        echo "앱 시작을 기다리는 중..."
        sleep 90
        echo "상태 확인을 수행하는 중..."
        curl -f "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/SimplePG/" || echo "상태 확인 실패 - 앱이 아직 시작 중일 수 있습니다"
                
    - name: 'Azure 로그아웃'
      run: |
        az logout
